"""Three-way temporal split with buffers.

Replaces the published scheme, in which "out-of-sample" meant the annual record
minus the 864 rows used for parameter identification -- 2.3% of CT-01 -- and the
same remaining record was used both to choose between candidate models and to
report the chosen model's accuracy.  Two reviewers independently objected; see
manuscript fixes M-09.

What is produced instead:

``identification``
    Fits parameters.

``selection``
    Chooses between candidates and any hyper-parameters.  Never used to report
    accuracy.

``test``
    Scored exactly once, at the end.  This is the number that goes in the paper.

Between consecutive segments a **buffer** is discarded.  Five-minute plant data
is strongly autocorrelated: without a gap the first test samples are simply the
continuation of the last identification samples -- same water temperatures, same
load, same weather -- and the split measures memory rather than generalisation.
The buffer must exceed the system's memory; 72 h is the default, covering a full
diurnal cycle plus thermal relaxation of the condenser loop.

Segments are also required to be *comparable*.  A test block confined to
February proves nothing about a model identified in August, so
:func:`coverage_report` summarises the driving conditions of each segment and
:meth:`SplitResult.comparability` flags segments whose ranges do not overlap.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Mapping, Sequence

import numpy as np
import pandas as pd

__all__ = [
    "SplitSpec",
    "SplitResult",
    "SEGMENTS",
    "build_split",
    "coverage_report",
    "seasonal_blocks",
    "proportional_blocks",
]

SEGMENTS = ("identification", "selection", "test")


@dataclass(frozen=True)
class SplitSpec:
    """Declarative split, normally read from ``project.yaml``.

    ``blocks`` maps a segment name to a list of ``(start, end)`` ISO dates, end
    exclusive.  When omitted the split is generated by
    :func:`seasonal_blocks`.
    """

    buffer_hours: float = 72.0
    mode: str = "proportional"                  # proportional | seasonal
    n_blocks: int = 12
    block_pattern: tuple[str, ...] = (
        "identification", "test", "selection", "test")
    blocks: Mapping[str, Sequence[tuple[str, str]]] | None = None
    # Sample counts, not durations. The defaults were originally written as
    # "24 h" and "one week" of five-minute data, which only means those
    # durations for a device that runs continuously. Site A's sparser pumps
    # retain 1,700-2,900 rows spread over 200-310 days, so a 2016-row test
    # segment would have to be 80% of their entire record -- they were being
    # refused for their duty cycle rather than for want of evidence.
    #
    # Kept deliberately conservative: of the five Site A pumps they exclude,
    # four are unusable on any reading (two have an empty selection segment,
    # one has 56 selection rows, one has a single row) and only CDWP_02, with
    # 221 test rows, is arguable.
    #
    # The principled refinement is samples-per-parameter -- YorkCalc fits 27
    # coefficients and Merkel four, so one number cannot serve both -- but the
    # split does not currently know the candidate's parameter count.
    min_identification_rows: int = 288
    min_selection_rows: int = 288
    min_test_rows: int = 2016
    seasonal_identification_months: tuple[int, ...] = (6, 11, 2)
    seasonal_selection_months: tuple[int, ...] = (8, 12)
    seasonal_block_days: int = 14

    @classmethod
    def from_mapping(cls, spec: Mapping | None) -> "SplitSpec":
        if not spec:
            return cls()
        blocks = spec.get("blocks")
        if blocks:
            blocks = {k: [tuple(p) for p in v] for k, v in blocks.items()}
        known = {f for f in cls.__dataclass_fields__ if f != "blocks"}
        kwargs = {k: v for k, v in spec.items() if k in known}
        if "seasonal_identification_months" in kwargs:
            kwargs["seasonal_identification_months"] = tuple(
                kwargs["seasonal_identification_months"])
        if "seasonal_selection_months" in kwargs:
            kwargs["seasonal_selection_months"] = tuple(
                kwargs["seasonal_selection_months"])
        if "block_pattern" in kwargs:
            kwargs["block_pattern"] = tuple(kwargs["block_pattern"])
        return cls(blocks=blocks, **kwargs)


@dataclass
class SplitResult:
    timestamps: pd.Series
    masks: dict[str, np.ndarray]
    buffer_mask: np.ndarray
    spec: SplitSpec
    warnings: list[str] = field(default_factory=list)

    def counts(self) -> dict[str, int]:
        out = {s: int(self.masks[s].sum()) for s in SEGMENTS}
        out["buffer"] = int(self.buffer_mask.sum())
        out["unused"] = int(len(self.timestamps) - sum(out.values()))
        return out

    @property
    def usable(self) -> bool:
        """Whether the device supports a scored, independent test segment."""
        c = self.counts()
        return (c["identification"] >= self.spec.min_identification_rows
                and c["selection"] >= self.spec.min_selection_rows
                and c["test"] >= self.spec.min_test_rows)

    @property
    def status(self) -> str:
        c = self.counts()
        if c["identification"] < self.spec.min_identification_rows:
            return "blocked_insufficient_identification"
        if not self.usable:
            return "identification_only"
        return "full_split"

    def comparability(self, frame: pd.DataFrame,
                      variables: Sequence[str]) -> pd.DataFrame:
        """Per-segment ranges of the driving variables.

        A split is only meaningful if the test segment exercises conditions the
        identification segment also saw; this table is the evidence for that and
        belongs in the supplementary material.
        """
        rows = []
        for seg in SEGMENTS:
            mask = self.masks[seg]
            for var in variables:
                if var not in frame.columns:
                    continue
                values = pd.to_numeric(frame.loc[mask, var], errors="coerce").dropna()
                if values.empty:
                    rows.append(dict(segment=seg, variable=var, n=0))
                    continue
                rows.append(dict(
                    segment=seg, variable=var, n=int(values.size),
                    minimum=float(values.min()), p05=float(values.quantile(0.05)),
                    median=float(values.median()),
                    p95=float(values.quantile(0.95)), maximum=float(values.max())))
        return pd.DataFrame(rows)


def _to_datetime(values) -> pd.Series:
    ts = pd.to_datetime(pd.Series(values), errors="coerce")
    if getattr(ts.dt, "tz", None) is not None:
        ts = ts.dt.tz_localize(None)
    return ts


def seasonal_blocks(timestamps: pd.Series, spec: SplitSpec
                    ) -> dict[str, list[tuple[pd.Timestamp, pd.Timestamp]]]:
    """Fixed-calendar blocks: identification in one set of months, selection in another.

    Only usable when every device shares roughly the same operating calendar.
    At Site A they do not -- the retained records span 28.8 days (CT-06) to
    348.3 days (CT-03), because towers are staged in and out -- so a fixed month
    list leaves some towers with no identification samples at all.  Kept for
    sites where it applies; :func:`proportional_blocks` is the default.
    """
    start, end = timestamps.min(), timestamps.max()
    span_days = (end - start).days
    width = pd.Timedelta(days=min(spec.seasonal_block_days, max(1, span_days // 12)))

    def blocks_for(months: Iterable[int]):
        out = []
        for month in months:
            candidates = timestamps[timestamps.dt.month == month]
            if candidates.empty:
                continue
            block_start = candidates.min()
            out.append((block_start, block_start + width))
        return out

    return {
        "identification": blocks_for(spec.seasonal_identification_months),
        "selection": blocks_for(spec.seasonal_selection_months),
    }


def proportional_blocks(timestamps: pd.Series, spec: SplitSpec
                        ) -> dict[str, list[tuple[pd.Timestamp, pd.Timestamp]]]:
    """Interleaved equal-duration blocks over each device's own record.

    The record is cut into ``n_blocks`` equal-duration slices and the slices are
    dealt out to the three segments in a fixed repeating pattern.  Every segment
    therefore samples the whole span of the record rather than one end of it,
    which is what makes the comparability table come out flat, and the scheme
    needs no assumption about which calendar months a given device ran in.

    Each block is then shrunk by half the buffer at both ends, so adjacent
    blocks of different segments end up a full ``buffer_hours`` apart and the
    cost is shared rather than charged entirely to the test segment.
    """
    start, end = timestamps.min(), timestamps.max()
    total = end - start
    if total <= pd.Timedelta(0):
        return {"identification": [], "selection": [], "test": []}

    n = max(len(spec.block_pattern), spec.n_blocks)
    width = total / n
    half_buffer = pd.Timedelta(hours=spec.buffer_hours) / 2
    if width <= 2 * half_buffer:
        # buffer would consume the blocks; fall back to a proportionally
        # scaled buffer so the split still exists on short records
        half_buffer = width * 0.1

    out: dict[str, list[tuple[pd.Timestamp, pd.Timestamp]]] = {
        s: [] for s in SEGMENTS}
    for i in range(n):
        segment = spec.block_pattern[i % len(spec.block_pattern)]
        if segment not in SEGMENTS:
            continue
        a = start + i * width + half_buffer
        b = start + (i + 1) * width - half_buffer
        if b > a:
            out[segment].append((a, b))
    return out


def build_split(timestamps, spec: SplitSpec | None = None) -> SplitResult:
    """Assign every sample to a segment, a buffer, or nothing.

    Buffers are carved out *after* the identification and selection blocks are
    placed, and always at the expense of the test segment -- discarding test
    samples is safe, whereas shrinking the identification block silently
    weakens the fit.
    """
    spec = spec or SplitSpec()
    ts = _to_datetime(timestamps).reset_index(drop=True)
    n = len(ts)
    warnings: list[str] = []
    valid = ts.notna().to_numpy()
    if not valid.any():
        raise ValueError("no parseable timestamps")

    if spec.blocks:
        declared = {seg: [(pd.Timestamp(a), pd.Timestamp(b))
                          for a, b in spec.blocks.get(seg, [])]
                    for seg in ("identification", "selection")}
        if spec.blocks.get("test"):
            declared["test"] = [(pd.Timestamp(a), pd.Timestamp(b))
                                for a, b in spec.blocks["test"]]
    elif spec.mode == "seasonal":
        declared = seasonal_blocks(ts.dropna(), spec)
    else:
        declared = proportional_blocks(ts.dropna(), spec)

    masks = {seg: np.zeros(n, bool) for seg in SEGMENTS}
    for seg in ("identification", "selection"):
        for a, b in declared.get(seg, []):
            masks[seg] |= (ts >= a).to_numpy() & (ts < b).to_numpy() & valid

    overlap = masks["identification"] & masks["selection"]
    if overlap.any():
        warnings.append(
            f"{int(overlap.sum())} samples were claimed by both identification "
            "and selection; assigned to identification")
        masks["selection"] &= ~masks["identification"]

    buffer_delta = pd.Timedelta(hours=spec.buffer_hours)
    buffer_mask = np.zeros(n, bool)
    for seg in ("identification", "selection"):
        for a, b in declared.get(seg, []):
            near = ((ts >= a - buffer_delta) & (ts < b + buffer_delta)).to_numpy()
            buffer_mask |= near & valid
    buffer_mask &= ~(masks["identification"] | masks["selection"])

    if declared.get("test"):
        for a, b in declared["test"]:
            masks["test"] |= (ts >= a).to_numpy() & (ts < b).to_numpy() & valid
        masks["test"] &= ~buffer_mask
        masks["test"] &= ~(masks["identification"] | masks["selection"])
    else:
        masks["test"] = (valid & ~buffer_mask
                         & ~masks["identification"] & ~masks["selection"])

    result = SplitResult(timestamps=ts, masks=masks, buffer_mask=buffer_mask,
                         spec=spec, warnings=warnings)
    counts = result.counts()
    for seg, floor in (("identification", spec.min_identification_rows),
                       ("selection", spec.min_selection_rows),
                       ("test", spec.min_test_rows)):
        if counts[seg] < floor:
            warnings.append(
                f"{seg} has {counts[seg]} samples, below the {floor} required; "
                f"status={result.status}")
    return result


def build_split_from_elapsed(seconds, spec: SplitSpec | None = None) -> SplitResult:
    """Split a record given as elapsed seconds rather than wall-clock stamps.

    The device engines carry a ``time_s`` column of real elapsed time including
    gaps, not absolute timestamps.  Anchoring it on an arbitrary epoch keeps one
    implementation of the split logic instead of two that can drift apart; the
    epoch never leaves this function.
    """
    elapsed = pd.to_numeric(pd.Series(seconds), errors="coerce")
    epoch = pd.Timestamp("2000-01-01")
    return build_split(epoch + pd.to_timedelta(elapsed, unit="s"), spec)


def coverage_report(frame: pd.DataFrame, result: SplitResult,
                    variables: Sequence[str]) -> pd.DataFrame:
    return result.comparability(frame, variables)
