source_csv: cooling_tower/CT_05.csv
timestamp: DateTime
columns:
  power_W:
    source: P/kw
    scale: 1000.0
  fan1_Hz:
    source: CT-2F02-A-VSD-STS.Present Value (Hz)
  fan2_Hz:
    source: CT-2F02-B-VSD-STS.Present Value (Hz)
  tcwr_C:
    source: CT-2F02-CDWR-WTS.Present Value (°C)
  tcws_1_C:
    source: CT-2F02-CDWS-WTS.Present Value (°C)
  run_signal:
    source: CT-2F02-A-VSD-STS.Present Value (Hz)
