source_csv: pump/CDWP_01.csv
timestamp: DateTime
columns:
  power_W:
    source: P/kw
    scale: 1000.0
  speed_Hz:
    source: CDWP-1E01-VSD-STS.Present Value (Hz)
  run_signal:
    source: CDWP-1E01-VSD-STS.Present Value (Hz)
